// Per-device tokens, and nothing else.
//
// There is no password and no account. A device token is 256 bits of entropy
// generated by this server, shown to its owner exactly once, and pasted into the
// phone's settings. That is the whole authentication model, which is why the
// file holds only a SHA-256 of each token: a copy of devices.json is therefore
// not a copy of everybody's credentials, and the tokens cannot be recovered from
// a backup of it.
//
// Two details are load-bearing:
//
//   * The comparison is constant-time. A token is a secret compared against a
//     secret, so a byte-at-a-time comparison is a byte-at-a-time oracle.
//   * A digest is computed even when the device is unknown, so an unknown device
//     and a wrong token take the same time. Otherwise the response time alone
//     says which device ids exist.

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { ErrorCode } from '../protocol/index.js';
import { TOKEN_SIZE } from '../protocol/seal.js';

const FILE_VERSION = 1;
const HASH_BYTES = 32;

export function newDeviceId() {
  return crypto.randomUUID();
}

export function newDeviceToken() {
  return crypto.randomBytes(TOKEN_SIZE).toString('base64url');
}

export function hashToken(token) {
  return crypto.createHash('sha256').update(String(token ?? ''), 'utf8').digest('hex');
}

function constantTimeEqualsHex(a, b) {
  const left = Buffer.from(String(a ?? ''), 'hex');
  const right = Buffer.from(String(b ?? ''), 'hex');
  if (left.length !== right.length || left.length === 0) return false;
  return crypto.timingSafeEqual(left, right);
}

export class DeviceStore {
  constructor(filePath) {
    this.filePath = filePath;
    this.data = { version: FILE_VERSION, devices: [] };
  }

  load() {
    if (!fs.existsSync(this.filePath)) {
      this.data = { version: FILE_VERSION, devices: [] };
      return this;
    }
    const raw = fs.readFileSync(this.filePath, 'utf8');
    let parsed;
    try {
      parsed = JSON.parse(raw);
    } catch (error) {
      throw new Error(`${this.filePath} is not valid JSON: ${error.message}`);
    }
    if (!parsed || !Array.isArray(parsed.devices)) {
      throw new Error(`${this.filePath} has no devices array`);
    }
    this.data = { version: FILE_VERSION, devices: parsed.devices };
    return this;
  }

  /** Written to a temporary file and renamed, so a crash cannot truncate the registry. */
  save() {
    const directory = path.dirname(this.filePath);
    fs.mkdirSync(directory, { recursive: true });
    const temporary = `${this.filePath}.${process.pid}.tmp`;
    fs.writeFileSync(temporary, `${JSON.stringify(this.data, null, 2)}\n`, { mode: 0o600 });
    fs.renameSync(temporary, this.filePath);
    return this;
  }

  /** Returns the token ONCE. It is not recoverable afterwards, by design. */
  add(label) {
    const deviceId = newDeviceId();
    const token = newDeviceToken();
    const device = {
      deviceId,
      label: String(label ?? '').slice(0, 120),
      tokenSha256: hashToken(token),
      createdAt: new Date().toISOString(),
      disabled: false,
    };
    this.data.devices.push(device);
    this.save();
    return { device, token };
  }

  find(deviceId) {
    return this.data.devices.find((device) => device.deviceId === deviceId) ?? null;
  }

  remove(deviceId) {
    const before = this.data.devices.length;
    this.data.devices = this.data.devices.filter((device) => device.deviceId !== deviceId);
    if (this.data.devices.length === before) return false;
    this.save();
    return true;
  }

  setDisabled(deviceId, disabled) {
    const device = this.find(deviceId);
    if (!device) return false;
    device.disabled = Boolean(disabled);
    this.save();
    return true;
  }

  /** Public view: the hash is never part of it. */
  list() {
    return this.data.devices.map((device) => ({
      deviceId: device.deviceId,
      label: device.label,
      createdAt: device.createdAt,
      disabled: Boolean(device.disabled),
    }));
  }

  get size() {
    return this.data.devices.length;
  }

  /**
   * Check a claimed token against a device id.
   *
   * Always returns one of ErrorCode's values rather than a boolean, because the
   * caller has to say WHY, and "unknown device" and "wrong token" are different
   * sentences for the person holding the phone -- one means the id is wrong, the
   * other means the token is.
   */
  verify(deviceId, token) {
    const claimedHash = hashToken(token);
    const device = this.find(deviceId);

    if (!device) {
      // Same work as the found case, so the timing does not leak existence.
      constantTimeEqualsHex(claimedHash, claimedHash.replace(/./g, '0'));
      return { ok: false, code: ErrorCode.UNKNOWN_DEVICE, device: null };
    }
    if (device.disabled) {
      constantTimeEqualsHex(claimedHash, device.tokenSha256);
      return { ok: false, code: ErrorCode.DISABLED_DEVICE, device: null };
    }
    if (!constantTimeEqualsHex(claimedHash, device.tokenSha256)) {
      return { ok: false, code: ErrorCode.BAD_TOKEN, device: null };
    }
    return { ok: true, code: 0, device: { deviceId: device.deviceId, label: device.label } };
  }
}

export { HASH_BYTES, constantTimeEqualsHex };
