// Per-device tokens, and nothing else.
//
// There is no password and no account. A device token is 256 bits of entropy
// generated by this server, shown to its owner exactly once, and pasted into the
// phone's settings. That is the whole authentication model, which is why the
// file holds only a SHA-256 of each token: a copy of devices.json is therefore
// not a copy of everybody's credentials, and the tokens cannot be recovered from
// a backup of it.
//
// THE TOKEN IS THE IDENTITY, AND IT BELONGS TO ONE DEVICE. A token is claimed by
// the first device id that presents it, and any other device id presenting it is
// refused. That is not a restriction bolted onto a working flow; it is what makes
// the token a credential rather than a shared password, and it is also what makes
// the phone's device id harmless to send in the clear -- an id is a name, the
// token is the secret. The one way a token moves is `bfwp-device release`, which
// an operator runs on purpose.
//
// Two details are load-bearing:
//
//   * The comparison is constant-time. A token is a secret compared against a
//     secret, so a byte-at-a-time comparison is a byte-at-a-time oracle.
//   * A digest is computed even when the device is unknown, so an unknown device
//     and a wrong token take the same time. Otherwise the response time alone
//     says which device ids exist.

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { ErrorCode } from '../protocol/index.js';
import { TOKEN_SIZE } from '../protocol/seal.js';

const FILE_VERSION = 1;
const HASH_BYTES = 32;

export function newDeviceId() {
  return crypto.randomUUID();
}

export function newDeviceToken() {
  return crypto.randomBytes(TOKEN_SIZE).toString('base64url');
}

export function hashToken(token) {
  return crypto.createHash('sha256').update(String(token ?? ''), 'utf8').digest('hex');
}

function constantTimeEqualsHex(a, b) {
  const left = Buffer.from(String(a ?? ''), 'hex');
  const right = Buffer.from(String(b ?? ''), 'hex');
  if (left.length !== right.length || left.length === 0) return false;
  return crypto.timingSafeEqual(left, right);
}

export class DeviceStore {
  constructor(filePath) {
    this.filePath = filePath;
    this.data = { version: FILE_VERSION, devices: [] };
    // mtime and size of the file this.data was read from, or null before the
    // first read. See refreshIfChanged.
    this.stamp = null;
  }

  load() {
    if (!fs.existsSync(this.filePath)) {
      this.data = { version: FILE_VERSION, devices: [] };
      this.stamp = null;
      return this;
    }
    const raw = fs.readFileSync(this.filePath, 'utf8');
    let parsed;
    try {
      parsed = JSON.parse(raw);
    } catch (error) {
      throw new Error(`${this.filePath} is not valid JSON: ${error.message}`);
    }
    if (!parsed || !Array.isArray(parsed.devices)) {
      throw new Error(`${this.filePath} has no devices array`);
    }
    this.data = { version: FILE_VERSION, devices: parsed.devices };
    this.stamp = this._stamp();
    return this;
  }

  /** `mtime:size`, or null when the file does not exist. */
  _stamp() {
    try {
      const stat = fs.statSync(this.filePath);
      return `${stat.mtimeMs}:${stat.size}`;
    } catch {
      return null;
    }
  }

  /**
   * Re-reads the file if it changed under us, and says whether it did.
   *
   * THE SERVER IS NOT THE ONLY WRITER. `bin/bfwp-device.js add` is a second
   * process writing this file directly -- same container, different process -- so
   * without this a device registered against a running server is invisible until
   * the next restart: an operator follows docs/DEPLOY.md exactly, pastes a
   * perfectly good token into the phone, and the server answers UNKNOWN_DEVICE.
   *
   * It is not only a convenience. `disable` is the command for a lost phone, and a
   * disable the running server cannot see is a lost phone that still connects --
   * which is a security-relevant staleness rather than an annoyance.
   *
   * Compared on mtime AND size, because a same-millisecond rewrite of the same
   * length is possible and this is the wrong place to be clever.
   *
   * Found by deploying it: the first smoke run against a live server refused a
   * device that `bfwp-device.js list` had just printed.
   */
  refreshIfChanged() {
    const stamp = this._stamp();
    if (stamp === this.stamp) return false;
    this.load();
    return true;
  }

  /** Written to a temporary file and renamed, so a crash cannot truncate the registry. */
  save() {
    const directory = path.dirname(this.filePath);
    fs.mkdirSync(directory, { recursive: true });
    const temporary = `${this.filePath}.${process.pid}.tmp`;
    fs.writeFileSync(temporary, `${JSON.stringify(this.data, null, 2)}\n`, { mode: 0o600 });
    fs.renameSync(temporary, this.filePath);
    // The file on disk is now what this store holds, so refreshIfChanged must not
    // report a change this process made itself.
    this.stamp = this._stamp();
    return this;
  }

  /** Returns the token ONCE. It is not recoverable afterwards, by design. */
  add(label) {
    const deviceId = newDeviceId();
    const token = newDeviceToken();
    const device = {
      deviceId,
      label: String(label ?? '').slice(0, 120),
      tokenSha256: hashToken(token),
      createdAt: new Date().toISOString(),
      disabled: false,
      // Who the token belongs to, written the first time it is used. Null means
      // "nobody has claimed it yet", including for a row an older version wrote,
      // which is why load() has nothing to migrate.
      boundDeviceId: null,
    };
    this.data.devices.push(device);
    this.save();
    return { device, token };
  }

  find(deviceId) {
    return this.data.devices.find((device) => device.deviceId === deviceId) ?? null;
  }

  /**
   * The row whose token digest matches, or null.
   *
   * EVERY ROW IS COMPARED, even once one has matched. Stopping at the first match
   * would make the response time say WHICH row matched, and the order of the
   * registry is decided by the operator rather than by the caller. The comparison
   * is constant-time, so with no early exit the whole lookup is.
   */
  findByToken(token) {
    const claimedHash = hashToken(token);
    let match = null;
    for (const device of this.data.devices) {
      if (constantTimeEqualsHex(claimedHash, device.tokenSha256)) match = device;
    }
    return match;
  }

  /**
   * Clears a token's binding so another device may claim it. The only way a token
   * moves, and deliberately an operator's command rather than something a phone
   * can do: a client that could release its own binding could also steal one.
   */
  releaseBinding(deviceId) {
    const device = this.find(deviceId);
    if (!device || !device.boundDeviceId) return false;
    device.boundDeviceId = null;
    this.save();
    return true;
  }

  /** Public view of one row: neither the token nor its digest is part of it. */
  _publicDevice(device) {
    return {
      deviceId: device.deviceId,
      label: device.label,
      boundDeviceId: device.boundDeviceId ?? null,
    };
  }

  remove(deviceId) {
    const before = this.data.devices.length;
    this.data.devices = this.data.devices.filter((device) => device.deviceId !== deviceId);
    if (this.data.devices.length === before) return false;
    this.save();
    return true;
  }

  setDisabled(deviceId, disabled) {
    const device = this.find(deviceId);
    if (!device) return false;
    device.disabled = Boolean(disabled);
    this.save();
    return true;
  }

  /** Public view: the hash is never part of it, and the binding is. */
  list() {
    return this.data.devices.map((device) => ({
      ...this._publicDevice(device),
      createdAt: device.createdAt,
      disabled: Boolean(device.disabled),
    }));
  }

  get size() {
    return this.data.devices.length;
  }

  /**
   * Check a token, and bind it to the device that presented it.
   *
   * The registry is searched BY TOKEN, not by the device id the client claimed.
   * The old rule could not authenticate a real handset at all: the phone generates
   * its own id (`RemoteEngine.LoadOrCreateDeviceId`), `bfwp-device add` created
   * another one, and no field of the phone's settings carried it -- so a handset
   * would have been refused UNKNOWN_DEVICE for as long as it was used, while the
   * smoke client, which takes its id from `add`, worked. An id is a name; the
   * token is the secret, which is what the header of this file says and what this
   * method now does.
   *
   * The first device to present a token claims it, and the claim is written to
   * disk before the session opens. A second device gets TOKEN_BOUND, and the
   * attempt does NOT move the binding: a token copied to another phone is refused
   * rather than silently shared, and a stolen token costs its owner nothing.
   *
   * Always returns one of ErrorCode's values rather than a boolean, because the
   * caller has to say WHY, and "this token is wrong", "this device was switched
   * off" and "this token belongs to another phone" are three different sentences
   * for the person holding the phone.
   */
  verify(deviceId, token) {
    const device = this.findByToken(token);
    if (!device) return { ok: false, code: ErrorCode.BAD_TOKEN, device: null };
    if (device.disabled) return { ok: false, code: ErrorCode.DISABLED_DEVICE, device: null };

    const claimedBy = String(deviceId ?? '');
    if (claimedBy.length === 0) {
      // A client that sends no id cannot claim anything. The phone refuses this
      // itself before it dials, so reaching here means another implementation.
      return { ok: false, code: ErrorCode.UNKNOWN_DEVICE, device: null };
    }

    if (!device.boundDeviceId) {
      device.boundDeviceId = claimedBy;
      this.save();
    } else if (device.boundDeviceId !== claimedBy) {
      return { ok: false, code: ErrorCode.TOKEN_BOUND, device: null };
    }

    return { ok: true, code: 0, device: this._publicDevice(device) };
  }
}

export { HASH_BYTES, constantTimeEqualsHex };
